### ISSUE TITLE
Gatsby build fail - error compiling the html.js

### ISSUE THREAD

**Issue by mcissel** [njosefbeck/gatsby-plugin-stripe-elements#1]
This plugin doesn't allow the Gatsby build process to complete

Steps to produce this:
```
gatsby new test
cd test
yarn add gatsby-plugin-stripe-elements
```
\- then add `gatsby-plugin-stripe-elements` to gatsby-config.js plugins array
```
gatsby develop
```

**Comment by njosefbeck** [comment]
Thanks for bringing this to my attention! This now should be fixed. I have verified this locally. If you have a moment to test on your end (I've updated the NPM package as well), and let me know if it's working for you, that'd be great! Thanks!

**Comment by mcissel** [comment]
It still doesn't work for me. I'm using:

- npm 3.10.10
- node 6.11.5
- yarn 1.3.2
- gatsby 1.1.28

**Comment by dougmacklin** [comment]
It's working fine for me with:

- npm 5.4.2
- node 8.8.1
- yarn 1.2.1
- gatsby 1.1.28

@mcissel did you already try manually deleting your `.cache` directory?

**Comment by njosefbeck** [comment]
@mcissel Thanks for checking! Can you verify that you have the updated version of the NPM package? (1.0.2)

If it's not up to date, here are instructions on how to update your NPM packages locally: https://docs.npmjs.com/getting-started/updating-local-packages

Also, Node has reached a new LTS, so you might also consider updating to that: https://nodejs.org/en/blog/release/v8.9.0/ (I'm not sure if that's causing your issue, but just thought I would mention it.)

**Comment by dougmacklin** [comment]
Hm I seem to be experiencing the same issue. I upgraded my node to 8.9.4, but no luck. Here is the full console output after running `gatsby develop`:

```
success delete html files from previous builds — 0.013 s
success open and validate gatsby-config.js — 0.005 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success copy gatsby files — 0.023 s
success onPreBootstrap — 0.011 s
success source and transform nodes — 0.025 s
success building schema — 0.087 s
success createLayouts — 0.023 s
success createPages — 0.005 s
success createPagesStatefully — 0.007 s
success onPreExtractQueries — 0.001 s
success update schema — 0.052 s
success extract queries from components — 0.075 s
success run graphql queries — 0.022 s
success write out page data — 0.002 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 1.932 s

error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  109 |  *
  110 |  * @internal
> 111 |  * @param {ReactNode} node Statically passed child of any type.
      |            ^
  112 |  * @param {*} parentType node's parent's type.
  113 |  */
  114 | function validateChildKeys(node, parentType) {


  WebpackError: 
  
  - ReactElementValidator.js:111 Parser.pp$4.raise
    ~/react/lib/ReactElementValidator.js:111:12
  
  - ReactNoopUpdateQueue.js:29 Parser.pp.unexpected
    ~/react/lib/ReactNoopUpdateQueue.js:29:1
  
  - traverseAllChildren.js:165 Parser.pp$3.parseExprAtom
    ~/react/lib/traverseAllChildren.js:165:1
  
  - traverseAllChildren.js:58 Parser.pp$3.parseExprSubscripts
    ~/react/lib/traverseAllChildren.js:58:12
  
  - traverseAllChildren.js:35 Parser.pp$3.parseMaybeUnary
    ~/react/lib/traverseAllChildren.js:35:1
  
  - ReactElementSymbol.js:2 Parser.pp$3.parseExprOps
    ~/react/lib/ReactElementSymbol.js:2:1
  
  - ReactCurrentOwner.js:16 Parser.pp$3.parseMaybeConditional
    ~/react/lib/ReactCurrentOwner.js:16:1
  
  - ReactElement.js:336 Parser.pp$3.parseMaybeAssign
    ~/react/lib/ReactElement.js:336:1
  
  
  - traverseAllChildren.js:144 Parser.pp$3.parseExprAtom
    ~/react/lib/traverseAllChildren.js:144:1
  
  - traverseAllChildren.js:58 Parser.pp$3.parseExprSubscripts
    ~/react/lib/traverseAllChildren.js:58:12
  
  - traverseAllChildren.js:35 Parser.pp$3.parseMaybeUnary
    ~/react/lib/traverseAllChildren.js:35:1
  
  - ReactElementSymbol.js:2 Parser.pp$3.parseExprOps
    ~/react/lib/ReactElementSymbol.js:2:1
  
  - ReactCurrentOwner.js:16 Parser.pp$3.parseMaybeConditional
    ~/react/lib/ReactCurrentOwner.js:16:1
  
  - ReactElement.js:336 Parser.pp$3.parseMaybeAssign
    ~/react/lib/ReactElement.js:336:1
  
  
  - traverseAllChildren.js:84 Parser.pp$3.parseSubscripts
    ~/react/lib/traverseAllChildren.js:84:24
  
  - traverseAllChildren.js:61 Parser.pp$3.parseExprSubscripts
    ~/react/lib/traverseAllChildren.js:61:13
  
  - traverseAllChildren.js:35 Parser.pp$3.parseMaybeUnary
    ~/react/lib/traverseAllChildren.js:35:1
  
  - ReactElementSymbol.js:2 Parser.pp$3.parseExprOps
    ~/react/lib/ReactElementSymbol.js:2:1
  
  - ReactCurrentOwner.js:16 Parser.pp$3.parseMaybeConditional
    ~/react/lib/ReactCurrentOwner.js:16:1
  
  - ReactElement.js:336 Parser.pp$3.parseMaybeAssign
    ~/react/lib/ReactElement.js:336:1
```

**Comment by njosefbeck** [comment]
Hm, sorry you're also now experiencing issues. I attempted to test this, but I can't even get Gatsby itself to properly build (outside of any plugins). Nor can I get a clean Gatsby site downloaded using the gatsby-cli. I will continue to try to replicate this issue over the weekend / week, and hopefully will be able to see what's going on.

In the mean time, there's this page: https://www.gatsbyjs.org/docs/debugging-html-builds/ which outlines some common issues when compiling the html.js. My code is not referencing window, so that can't be it. Hope to be able to debug the issue once I can get Gatsby up and running locally on my machine. :)

**Comment by njosefbeck** [comment]
So an update! I was able to get `gatsby build` and `gatsby develop` to run fine when I added the plugin manually, but it still doesn't work when I attempt to use the plugin via the npm package.

To use the plugin outside of NPM, you can create a plugins directory at the root of your Gatsby site (outside of the "src" directory), and then you can clone this repo into there. Then use `npm remove gatsby-plugin-stripe-elements` to remove the NPM package. You shouldn't have to update your Gatsby config.

If someone could try doing it this way and verify that it also works for them, that'd be great. Otherwise I'll keep digging... as my plugin code in this repo and what's up on NPM is the same.

**Comment by njosefbeck** [comment]
@mcissel @dougmacklin Hello! I've finally gotten around to figuring out this issue. If you wouldn't mind getting the latest version of this plugin from npm and testing to see if the build compiles properly, that'd be great. Thanks!

**Comment by njosefbeck** [comment]
This seems to be fixed for me in my own testing, so closing this.

**Comment by nrakochy** [comment]
Hi there, any chance you could document how you fixed this error? Ran across this same issue with a different plugin, and would appreciate any insight into how to fix it. Thanks.

**Comment by nrakochy** [comment]
I do appreciate the insight. My project failed to compile after adding a couple plugins, so presumably the server side rendering was not built out correctly in one of them. Thanks for the prompt feedback...

**Comment by njosefbeck** [comment]
Happy to help!
